#+TITLE: Mr. Whatsit
#+DESCRIPTION: Name Inspired by the series Stranger Things S5
#+AUTHOR: devlinman

* Contents :TOC_1:
- [[#about-whatsit][About Whatsit]]
- [[#wiki--documentation][Wiki & Documentation]]
- [[#improvements-in-v-40x][Improvements in v 4.0.x]]
- [[#install][Install]]
- [[#future-updates][Future updates]]
- [[#licenses][LICENSES]]

* About Whatsit

+ A lightweight, native desktop client for WhatsApp Web built with ~Qt 6~ and ~Qt WebEngine~, and is *NOT* Electron-based.

+ I have tried many Whatsapp web clients, but none of them are fast and light. None of them felt right...

+ My setup is Arch-KDE Plasma-Wayland. If your setup is similar, the app should work well.

+ In =v3.x.x=, additional features such as memory kill switch and custom app and tray icons, etc.
  You may call these features bloat, but I like to have those. If you don't want those, use lower versions of the app.

+ If you want the minimal and bare version, use =v1.0.1=. Tray icon and Notifications are implemented in =v2.0.0=.

** Features
+ Native: Qt 6 & Qt WebEngine-based
+ Persistent login and chat storage
+ Uses standard XDG directories
+ KDE / Wayland friendly
+ KDE Native Notification support
+ Reduce memory usage & kill switch
+ Opens whatsapp links from browsers to send messages.

* Wiki & Documentation

+ Check the [[https://github.com/devlinman/whatsit/wiki][wiki docs]] for more information.

*** Now, Notes is available from  [[https://github.com/devlinman/whatsit/wiki/Notes][wiki docs - Notes]].
+ It contains important information about the working of the app.
+ It is recommended to have a look.

* Improvements in v 4.0.x
*** MAJOR REGRESSION
+ Dark mode was already properly implemented by  whatsapp web itself. No need to confuse users further with JS injection.
+ *Regression: ALL (Including Dark Mode) JS injection is removed.*
+ Titlebar menu option and Config file key value are also removed as well.

+ The app is more secure now (Not that it wasn't before...), offering a more vanilla experience.

+ Dark Mode can be directly enabled from whatsapp settings, and that setting is persistent anyway.

+ If any problem occurs, use =Reload Config and Cache= option. If problem persists, start an issue on github.

+ You are free, and you are also encouraged to examine the source code to verify the security of the app.
  Essentially, User data (private messages) must not be exposed, unless for debugging purposes in dev-builds.

+ The code is commented out for reference, and it will be removed in next minor update.

+ If you want to examine the changes, go through the corresponding commit. In particular, check =webenginehelper.cpp= for changes regarding JS.

*** Qt Licensing
+ Added 3rd party licenses. check the LICENSES section below.

*** Icons
+ Added icons for titlebar menu buttons.
*** Tray icon in Hyprland (v4.0.1)
+ =Tray icon is not visible in waybar with hyprland=: closed. Tray manager updated. It now works on hyprland.

* Install
** Install From AUR
+ Now available from AUR - =whatsit-git=. [[https://aur.archlinux.org/packages/whatsit-git][AUR Package.]]
+ Builds from latest commit from git on default branch (master).

#+begin_src shell
yay -S whatsit-git
#+end_src

** Please refer to [[https://github.com/devlinman/whatsit/wiki ][wiki docs]] for more information on Build & Install.


* TODO Future updates
+ [ ] Delete debug file on app/profile change.
+ [ ] Notifcations via freedesktop.
+ [ ] Command-line info - =version=, =help= =show/hide=, etc.
+ [ ] RSS <-> PSS memory estimation method option??

* LICENSES
+ This project (binary/source code) is licensed under the MIT license, compliant with the third-party licenses mentioned below.
+ Check Licensing information at [[./LICENSES/LICENSE][LICENSE]].
+ *Copyright Disclaimer: Whatsapp is not owned by me.*
+ The [[./resources/][icons]] used in this project were grabbed off the internet.

**** tldr;
**** Use this app at your own risk.
**** I will not be liable for any damages.

*** Third-Party Licenses

+ This project uses the Qt framework (Qt6), including QtWebEngine, by dynamically linking against them.

+ Check [[./LICENSES/Qt-NOTICE.txt][Qt NOTICE]] for more information. Qt is licensed under the GNU Lesser General Public License v3 ([[./LICENSES/LGPL-3.0.txt][LGPL v3]]).

+ Check your Qt licensing using a command like this.

  #+begin_src shell
$ pacman -Qi qt6-webengine | grep License -A1
Licenses        : GPL-3.0-only  LGPL-3.0-only  LicenseRef-Qt-Commercial  Qt-GPL-exception-1.0
Groups          : qt6
  #+end_src

+ Qt source code is available from:
https://code.qt.io/
https://download.qt.io/
